import { Conversation, Message } from '@/types';

export const mockMessages: Message[] = [
  {
    id: 'm1',
    conversationId: 'c1',
    senderId: '1',
    receiverId: '101',
    type: 'text',
    content: "Hi there! I saw your post about the new film project. I'd love to learn more about the casting opportunities.",
    createdAt: Date.now() - 86400000, // 1 day ago
    readAt: Date.now() - 85000000,
  },
  {
    id: 'm2',
    conversationId: 'c1',
    senderId: '101',
    receiverId: '1',
    type: 'text',
    content: "Hello Emma! Thanks for reaching out. We're looking for a lead actress for our upcoming feature film. Would you be interested in auditioning?",
    createdAt: Date.now() - 84000000,
    readAt: Date.now() - 83000000,
  },
  {
    id: 'm3',
    conversationId: 'c1',
    senderId: '1',
    receiverId: '101',
    type: 'text',
    content: "Absolutely! I'd be very interested in auditioning. Could you share more details about the character and the project?",
    createdAt: Date.now() - 82000000,
    readAt: Date.now() - 81000000,
  },
  {
    id: 'm4',
    conversationId: 'c1',
    senderId: '101',
    receiverId: '1',
    type: 'text',
    content: "Of course! The film is a psychological thriller titled 'Echoes of Tomorrow'. The character we're casting for is a 28-year-old psychologist who discovers her patients are connected to a mysterious event. We'll be shooting in Los Angeles starting next month. Would you be available for an in-person audition next week?",
    createdAt: Date.now() - 80000000,
    readAt: Date.now() - 79000000,
  },
  {
    id: 'm5',
    conversationId: 'c1',
    senderId: '1',
    receiverId: '101',
    type: 'text',
    content: "That sounds perfect for me! Yes, I'm available for an audition next week. Should I prepare a specific scene or monologue?",
    createdAt: Date.now() - 78000000,
    readAt: Date.now() - 77000000,
  },
  {
    id: 'm6',
    conversationId: 'c1',
    senderId: '101',
    receiverId: '1',
    type: 'text',
    content: "Great! We'll send you some sides to prepare. Also, could you send us your updated headshots and resume?",
    createdAt: Date.now() - 76000000,
    readAt: Date.now() - 75000000,
  },
  {
    id: 'm7',
    conversationId: 'c1',
    senderId: '1',
    receiverId: '101',
    type: 'text',
    content: "Of course! I'll email those to you right away. Looking forward to the audition!",
    createdAt: Date.now() - 74000000,
    readAt: Date.now() - 73000000,
  },
  {
    id: 'm8',
    conversationId: 'c1',
    senderId: '101',
    receiverId: '1',
    type: 'text',
    content: "Perfect! We're excited to see what you bring to the character. We'll be in touch with the audition details soon.",
    createdAt: Date.now() - 72000000,
    readAt: Date.now() - 71000000,
  },
  
  // Conversation 2
  {
    id: 'm9',
    conversationId: 'c2',
    senderId: '1',
    receiverId: '3',
    type: 'text',
    content: "Hi Sophia! I loved your recent editorial shoot. The styling was amazing!",
    createdAt: Date.now() - 172800000, // 2 days ago
    readAt: Date.now() - 171800000,
  },
  {
    id: 'm10',
    conversationId: 'c2',
    senderId: '3',
    receiverId: '1',
    type: 'text',
    content: "Thanks Emma! It was such a fun shoot. How have you been?",
    createdAt: Date.now() - 171000000,
    readAt: Date.now() - 170000000,
  },
  {
    id: 'm11',
    conversationId: 'c2',
    senderId: '1',
    receiverId: '3',
    type: 'text',
    content: "I've been great! Just finished a commercial shoot last week. Hey, I wanted to ask if you'd be interested in collaborating on a photoshoot I'm planning? It's for a charity event.",
    createdAt: Date.now() - 169000000,
    readAt: Date.now() - 168000000,
  },
  {
    id: 'm12',
    conversationId: 'c2',
    senderId: '3',
    receiverId: '1',
    type: 'text',
    content: "That sounds interesting! Tell me more about the charity and the concept you have in mind.",
    createdAt: Date.now() - 167000000,
    readAt: Date.now() - 166000000,
  },
  {
    id: 'm13',
    conversationId: 'c2',
    senderId: '1',
    receiverId: '3',
    type: 'text',
    content: "It's for the Ocean Conservation Foundation. The concept is 'Beauty of the Sea' - we'll be doing an underwater-inspired shoot, but on land with creative lighting and props. We're aiming to raise awareness about ocean pollution.",
    createdAt: Date.now() - 165000000,
    readAt: Date.now() - 164000000,
  },
  {
    id: 'm14',
    conversationId: 'c2',
    senderId: '3',
    receiverId: '1',
    type: 'text',
    content: "I love that! Ocean conservation is a cause I'm passionate about. Count me in! When are you planning to do this?",
    createdAt: Date.now() - 163000000,
    readAt: Date.now() - 162000000,
  },
  {
    id: 'm15',
    conversationId: 'c2',
    senderId: '1',
    receiverId: '3',
    type: 'text',
    content: "Amazing! We're looking at the first weekend of next month. I'll send you more details soon. Thanks for being on board!",
    createdAt: Date.now() - 161000000,
    readAt: Date.now() - 160000000,
  },
  {
    id: 'm16',
    conversationId: 'c2',
    senderId: '3',
    receiverId: '1',
    type: 'text',
    content: "Sounds perfect! Looking forward to it. Let's create something beautiful for a good cause!",
    createdAt: Date.now() - 159000000,
    readAt: Date.now() - 158000000,
  },
  
  // Conversation 3 (unread messages)
  {
    id: 'm17',
    conversationId: 'c3',
    senderId: '102',
    receiverId: '1',
    type: 'text',
    content: "Hello Emma, this is Sarah from Elite Talent Agency. I've been following your work and I'm impressed with your range as an actress. I'd like to discuss potential representation.",
    createdAt: Date.now() - 43200000, // 12 hours ago
    readAt: undefined,
  },
  {
    id: 'm18',
    conversationId: 'c3',
    senderId: '102',
    receiverId: '1',
    type: 'text',
    content: "We have several casting opportunities that might be perfect for you, including a supporting role in an upcoming Netflix series. Please let me know if you'd be interested in discussing this further.",
    createdAt: Date.now() - 39600000, // 11 hours ago
    readAt: undefined,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    participants: ['1', '101'],
    lastMessage: mockMessages.find(m => m.id === 'm8'),
    createdAt: Date.now() - 86400000, // 1 day ago
    updatedAt: Date.now() - 72000000,
  },
  {
    id: 'c2',
    participants: ['1', '3'],
    lastMessage: mockMessages.find(m => m.id === 'm16'),
    createdAt: Date.now() - 172800000, // 2 days ago
    updatedAt: Date.now() - 159000000,
  },
  {
    id: 'c3',
    participants: ['1', '102'],
    lastMessage: mockMessages.find(m => m.id === 'm18'),
    createdAt: Date.now() - 43200000, // 12 hours ago
    updatedAt: Date.now() - 39600000,
    pinnedBy: ['1'],
  },
];

export default { mockConversations, mockMessages };